/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_jamilvilleda_programacion2;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Jamil
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        adminUsuarioAdmin.cargarArchivo();
        adminUsuarioAdmin.escrbirArchivo();
        adminUsuarioNormal.cargarArchivo();
        adminUsuarioNormal.escrbirArchivo();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crearUsuario = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dt_fechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ps_contraseña = new javax.swing.JPasswordField();
        jLabel34 = new javax.swing.JLabel();
        rb_Administrador = new javax.swing.JRadioButton();
        rb_Normal = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        tf_correoElectronico = new javax.swing.JTextField();
        boton_registrarse = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lb_fotopapeleta = new javax.swing.JLabel();
        bt_seleccionarimagen = new javax.swing.JButton();
        jd_logIn = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_usuarioLogIn = new javax.swing.JTextField();
        tf_contraseñaLogIn = new javax.swing.JTextField();
        bt_iniciarSesion = new javax.swing.JButton();
        jd_UsuarioAdministrador = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_usuariosGenerales = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jd_UsuarioNormal = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_informacionPersonalUsuarioComun = new javax.swing.JTable();
        bt_modificarInformacion = new javax.swing.JButton();
        bt_eliminarseSistema = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtree_solicitudesAmistad = new javax.swing.JTree();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtree_listaAmigos = new javax.swing.JTree();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_usuariosSolicitudes = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        bt_agregarAmigos = new javax.swing.JButton();
        jpopup_opciones = new javax.swing.JPopupMenu();
        jmi_aceptar = new javax.swing.JMenuItem();
        jmi_rechazar = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Registrar Usuario");

        jLabel2.setText("Nombre");

        jLabel8.setText("Fecha de Nacimento");

        jLabel10.setText("Usuario");

        jLabel11.setText("Contraseña");

        jLabel34.setText("Tipo de Usuario");

        rb_Administrador.setText("Administrador");

        rb_Normal.setText("Normal");
        rb_Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_NormalActionPerformed(evt);
            }
        });

        jLabel4.setText("Correo Electronico");

        boton_registrarse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boton_registrarse.setText("Registrar Usuario");
        boton_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_registrarseMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel15.setText("Imagen:");

        lb_fotopapeleta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bt_seleccionarimagen.setText("Seleccionar Imagen");
        bt_seleccionarimagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_seleccionarimagenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearUsuarioLayout = new javax.swing.GroupLayout(jd_crearUsuario.getContentPane());
        jd_crearUsuario.getContentPane().setLayout(jd_crearUsuarioLayout);
        jd_crearUsuarioLayout.setHorizontalGroup(
            jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel6))
                            .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                                .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dt_fechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ps_contraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_correoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                                            .addComponent(rb_Administrador)
                                            .addGap(18, 18, 18)
                                            .addComponent(rb_Normal)))
                                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                        .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel15))
                            .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(bt_seleccionarimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addComponent(lb_fotopapeleta, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crearUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(boton_registrarse)
                .addGap(170, 170, 170))
        );
        jd_crearUsuarioLayout.setVerticalGroup(
            jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(64, 64, 64)
                        .addComponent(bt_seleccionarimagen))
                    .addGroup(jd_crearUsuarioLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(dt_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ps_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(rb_Administrador)
                            .addComponent(rb_Normal))
                        .addGap(24, 24, 24)
                        .addGroup(jd_crearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_correoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(lb_fotopapeleta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(boton_registrarse)
                .addGap(17, 17, 17))
        );

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Inicio de Sesion");

        jLabel5.setText("Usuario: ");

        jLabel7.setText("Contraseña:");

        bt_iniciarSesion.setText("Iniciar Sesion");
        bt_iniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_iniciarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_logInLayout = new javax.swing.GroupLayout(jd_logIn.getContentPane());
        jd_logIn.getContentPane().setLayout(jd_logInLayout);
        jd_logInLayout.setHorizontalGroup(
            jd_logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_logInLayout.createSequentialGroup()
                .addGroup(jd_logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_logInLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jd_logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(jd_logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_usuarioLogIn)
                            .addComponent(tf_contraseñaLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                    .addGroup(jd_logInLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel3))
                    .addGroup(jd_logInLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(bt_iniciarSesion)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jd_logInLayout.setVerticalGroup(
            jd_logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_logInLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(43, 43, 43)
                .addGroup(jd_logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_usuarioLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jd_logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(tf_contraseñaLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(bt_iniciarSesion)
                .addGap(57, 57, 57))
        );

        jt_usuariosGenerales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Correo", "Fecha", "Usuario", "Contraseña"
            }
        ));
        jScrollPane1.setViewportView(jt_usuariosGenerales);

        jLabel9.setText("Lista de usuarios en el sistema");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel9)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Visualizar Usuarios en el Sistema", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ver Publicaciones", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 595, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        javax.swing.GroupLayout jd_UsuarioAdministradorLayout = new javax.swing.GroupLayout(jd_UsuarioAdministrador.getContentPane());
        jd_UsuarioAdministrador.getContentPane().setLayout(jd_UsuarioAdministradorLayout);
        jd_UsuarioAdministradorLayout.setHorizontalGroup(
            jd_UsuarioAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jd_UsuarioAdministradorLayout.setVerticalGroup(
            jd_UsuarioAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jButton3.setText("Publicar");

        jLabel12.setText("Publicaciones");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jButton3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        jTabbedPane2.addTab("Publicar Contenido", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Ver Lista de Publicaciones", jPanel5);

        jt_informacionPersonalUsuarioComun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Correo", "Fecha Nacimiento", "Usuario", "Contraseña"
            }
        ));
        jScrollPane2.setViewportView(jt_informacionPersonalUsuarioComun);

        bt_modificarInformacion.setText("Modificar Informacion");
        bt_modificarInformacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificarInformacionMouseClicked(evt);
            }
        });

        bt_eliminarseSistema.setText("Eliminarse del Sistema");
        bt_eliminarseSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarseSistemaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(bt_modificarInformacion)
                        .addGap(70, 70, 70)
                        .addComponent(bt_eliminarseSistema)
                        .addGap(16, 16, 16))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_eliminarseSistema)
                    .addComponent(bt_modificarInformacion))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Informacion Personal", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Ver lista de problemas", jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Publicaciones", jPanel9);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Solicitudes de Amistad");
        jtree_solicitudesAmistad.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree_solicitudesAmistad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree_solicitudesAmistadMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtree_solicitudesAmistad);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Lista de Amigos");
        jtree_listaAmigos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane5.setViewportView(jtree_listaAmigos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Solicitudes de amistad", jPanel6);

        jt_usuariosSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Usuario"
            }
        ));
        jScrollPane6.setViewportView(jt_usuariosSolicitudes);

        jLabel13.setText("Lista de Usuarios en el Sistema");

        bt_agregarAmigos.setText("Agregar Amigos");
        bt_agregarAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarAmigosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_agregarAmigosMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel13))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(bt_agregarAmigos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel13)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(bt_agregarAmigos)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Solicitudes", jPanel10);

        javax.swing.GroupLayout jd_UsuarioNormalLayout = new javax.swing.GroupLayout(jd_UsuarioNormal.getContentPane());
        jd_UsuarioNormal.getContentPane().setLayout(jd_UsuarioNormalLayout);
        jd_UsuarioNormalLayout.setHorizontalGroup(
            jd_UsuarioNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jd_UsuarioNormalLayout.setVerticalGroup(
            jd_UsuarioNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        jmi_aceptar.setText("Agregar a mis amigos");
        jmi_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_aceptarMouseClicked(evt);
            }
        });
        jpopup_opciones.add(jmi_aceptar);

        jmi_rechazar.setText("Rechazar solicitud de amistad");
        jmi_rechazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmi_rechazarMouseClicked(evt);
            }
        });
        jpopup_opciones.add(jmi_rechazar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Iniciar Sesion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear una cuenta");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido al Sistema");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addGap(92, 92, 92)
                .addComponent(jButton2)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_NormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_NormalActionPerformed

    private void boton_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_registrarseMouseClicked
        try {
            if (rb_Normal.isSelected()) {
                UsuarioNormal usuarioM = new UsuarioNormal(tf_nombre.getText(), tf_correoElectronico.getText(), dt_fechaNacimiento.getDate(),
                        tf_usuario.getText(), ps_contraseña.getText(), lb_fotopapeleta.getIcon(), false);
                adminUsuarioNormal.setUsuarioNormal(usuarioM);
                adminUsuarioNormal.escrbirArchivo();
                Image img = Toolkit.getDefaultToolkit().createImage("./default.jpeg").getScaledInstance(lb_fotopapeleta.getWidth(), lb_fotopapeleta.getHeight(), Image.SCALE_DEFAULT);
                lb_fotopapeleta.setIcon(new ImageIcon(img));
                JOptionPane.showMessageDialog(null, "Se ha guardado el usuario normal correctamente. ");
                tf_nombre.setText("");
                tf_correoElectronico.setText("");
                tf_usuario.setText("");
                ps_contraseña.setText("");

            }
            if (rb_Administrador.isSelected()) {
                UsuarioAdministrador usuarioM = new UsuarioAdministrador(tf_nombre.getText(), tf_correoElectronico.getText(), dt_fechaNacimiento.getDate(),
                        tf_usuario.getText(), ps_contraseña.getText(), lb_fotopapeleta.getIcon(), false);
                adminUsuarioAdmin.setUsuarioAdmin(usuarioM);
                adminUsuarioAdmin.escrbirArchivo();
                Image img = Toolkit.getDefaultToolkit().createImage("./default.jpeg").getScaledInstance(lb_fotopapeleta.getWidth(), lb_fotopapeleta.getHeight(), Image.SCALE_DEFAULT);
                lb_fotopapeleta.setIcon(new ImageIcon(img));
                JOptionPane.showMessageDialog(null, "Se ha guardado el usuario administrativo correctamente. ");
                tf_nombre.setText("");
                tf_correoElectronico.setText("");
                tf_usuario.setText("");
                ps_contraseña.setText("");
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_boton_registrarseMouseClicked

    private void bt_seleccionarimagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_seleccionarimagenMouseClicked

        try {
            JFileChooser fc = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "jpeg", "gif");
            fc.setFileFilter(filtro);
            File archivo;
            int op = fc.showOpenDialog(this);
            if (op == JFileChooser.APPROVE_OPTION) {
                archivo = fc.getSelectedFile();
                Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(lb_fotopapeleta.getWidth(), lb_fotopapeleta.getHeight(), Image.SCALE_DEFAULT);
                this.lb_fotopapeleta.setIcon(new ImageIcon(img));
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_bt_seleccionarimagenMouseClicked

    private void bt_iniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_iniciarSesionMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) jt_usuariosGenerales.getModel();
        DefaultTableModel modelo1 = (DefaultTableModel) jt_informacionPersonalUsuarioComun.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) jt_usuariosSolicitudes.getModel();

        for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) { //Verifica en la lista de usuarios contra y usuario
            if (tf_usuarioLogIn.getText().equals(adminUsuarioNormal.getUsuarioNormal().get(i).getNombreUsuario())) {
                System.out.println("Correcto1");
                if (tf_contraseñaLogIn.getText().equals(adminUsuarioNormal.getUsuarioNormal().get(i).getContraseña())) {
                    System.out.println("Correcto2");
                    JOptionPane.showMessageDialog(this, "Bienvenido al sistema " + adminUsuarioNormal.getUsuarioNormal().get(i).getNombreCompleto());

                    jd_logIn.dispose();
                    modelo2.setRowCount(0);

                    for (int j = 0; j < adminUsuarioNormal.getUsuarioNormal().size(); j++) { //Que no se repita el nombre en jt
                        if (i != j) {
                            String[] newrow = {adminUsuarioNormal.getUsuarioNormal().get(j).getNombreCompleto(),
                                adminUsuarioNormal.getUsuarioNormal().get(j).getNombreUsuario()};
                            modelo2.addRow(newrow);
                            jt_usuariosSolicitudes.setModel(modelo2);
                        }

                    }
                    modelo1.setRowCount(0);
                    String[] newrow = {adminUsuarioNormal.getUsuarioNormal().get(i).getNombreCompleto(), adminUsuarioNormal.getUsuarioNormal().get(i).getCorreoElectronico(),
                        adminUsuarioNormal.getUsuarioNormal().get(i).getFecha().toString(), adminUsuarioNormal.getUsuarioNormal().get(i).getNombreUsuario(),
                        adminUsuarioNormal.getUsuarioNormal().get(i).getContraseña()};
                    modelo1.addRow(newrow);

                    jt_informacionPersonalUsuarioComun.setModel(modelo);
                    jd_UsuarioNormal.setModal(true);
                    jd_UsuarioNormal.pack();
                    jd_UsuarioNormal.setLocationRelativeTo(null);
                    jd_UsuarioNormal.setVisible(true);
                }
            }
        }

        for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) {
            for (int j = 0; j < adminUsuarioNormal.getUsuarioNormal().get(i).getSolicitudes().size(); j++) {
                if (adminUsuarioNormal.getUsuarioNormal().get(i).getNombreUsuario().equals(tf_usuarioLogIn.getText())) {
                    DefaultMutableTreeNode solicitud;
                    DefaultTreeModel modeloarbol = (DefaultTreeModel) jtree_solicitudesAmistad.getModel();
                    DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloarbol.getRoot();
                    solicitud = new DefaultMutableTreeNode(adminUsuarioNormal.getUsuarioNormal().get(i).getSolicitudes().get(j));
                    raiz.add(solicitud);
                    modeloarbol.reload();
                }
            }
        }

        for (int i = 0; i < adminUsuarioAdmin.getUsuarioAdmin().size(); i++) {
            if (tf_usuarioLogIn.getText().equals(adminUsuarioAdmin.getUsuarioAdmin().get(i).getNombreUsuario())) {
                System.out.println("Correcto1");
                if (tf_contraseñaLogIn.getText().equals(adminUsuarioAdmin.getUsuarioAdmin().get(i).getContraseña())) {
                    System.out.println("Correcto2");
                    JOptionPane.showMessageDialog(this, "Bienvenido al sistema administrativo " + adminUsuarioAdmin.getUsuarioAdmin().get(i).getNombreCompleto());
                    modelo.setRowCount(0);
                    for (int j = 0; j < adminUsuarioNormal.getUsuarioNormal().size(); j++) {
                        String[] newrow = {adminUsuarioNormal.getUsuarioNormal().get(j).getNombreCompleto(), adminUsuarioNormal.getUsuarioNormal().get(j).getCorreoElectronico(),
                            adminUsuarioNormal.getUsuarioNormal().get(j).getFecha().toString(), adminUsuarioNormal.getUsuarioNormal().get(j).getNombreUsuario(),
                            adminUsuarioNormal.getUsuarioNormal().get(j).getContraseña()};
                        modelo.addRow(newrow);
                        jt_usuariosGenerales.setModel(modelo);
                    }

                    jd_logIn.dispose();
                    jd_UsuarioAdministrador.pack();
                    jd_UsuarioAdministrador.setModal(true);
                    jd_UsuarioAdministrador.setVisible(true);
                }
            }
        }
        tf_usuarioLogIn.setText("");
        tf_contraseñaLogIn.setText("");


    }//GEN-LAST:event_bt_iniciarSesionMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jd_crearUsuario.setModal(true);
        jd_crearUsuario.pack();
        jd_crearUsuario.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jd_logIn.setModal(true);
        jd_logIn.pack();
        jd_logIn.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void bt_modificarInformacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificarInformacionMouseClicked
        try {
            if (jt_informacionPersonalUsuarioComun.getSelectedRow() >= 0) {
                String nombreModificar = JOptionPane.showInputDialog(null, "Ingrese su nombre");
                DefaultTableModel modelo = (DefaultTableModel) jt_informacionPersonalUsuarioComun.getModel();
                String nombre = JOptionPane.showInputDialog(null, "Ingrese el nuevo nombre a agregarse");
                String usuario = JOptionPane.showInputDialog(null, "Ingrese el nuevo nombre de usuario a agregarse");
                String correo = JOptionPane.showInputDialog(null, "Ingrese el nuevo correo de usuario a agregarse");
                String contra = JOptionPane.showInputDialog(null, "Ingrese la nueva contraseña de usuario");

                modelo.setValueAt(nombre, jt_informacionPersonalUsuarioComun.getSelectedRow(), 0);
                modelo.setValueAt(correo, jt_informacionPersonalUsuarioComun.getSelectedRow(), 1);
                modelo.setValueAt(usuario, jt_informacionPersonalUsuarioComun.getSelectedRow(), 3);
                modelo.setValueAt(contra, jt_informacionPersonalUsuarioComun.getSelectedRow(), 4);

                jt_informacionPersonalUsuarioComun.setModel(modelo);

                adminUsuarioNormal.cargarArchivo();
                for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) {
                    if (adminUsuarioNormal.getUsuarioNormal().get(i).getNombreCompleto().equals(nombreModificar)) {
                        adminUsuarioNormal.getUsuarioNormal().get(i).setNombreCompleto(nombre);
                        adminUsuarioNormal.getUsuarioNormal().get(i).setCorreoElectronico(correo);
                        adminUsuarioNormal.getUsuarioNormal().get(i).setNombreUsuario(usuario);
                        adminUsuarioNormal.getUsuarioNormal().get(i).setContraseña(contra);
                    }
                }
                adminUsuarioNormal.escrbirArchivo();
                JOptionPane.showMessageDialog(null, "Se ha modificado el usuario correctamente. ");
            }

        } catch (Exception e) {

        }    }//GEN-LAST:event_bt_modificarInformacionMouseClicked

    private void bt_eliminarseSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarseSistemaMouseClicked
        try {
            if (jt_informacionPersonalUsuarioComun.getSelectedRow() >= 0) {
                DefaultTableModel modelo = (DefaultTableModel) jt_informacionPersonalUsuarioComun.getModel();
                modelo.removeRow(jt_informacionPersonalUsuarioComun.getSelectedRow());
                jt_informacionPersonalUsuarioComun.setModel(modelo);
                adminUsuarioNormal.cargarArchivo();
                String nombreModificar = JOptionPane.showInputDialog(null, "Ingrese su nombre porfavor: ");
                for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) {
                    if (adminUsuarioNormal.getUsuarioNormal().get(i).getNombreCompleto().equals(nombreModificar)) {
                        adminUsuarioNormal.getUsuarioNormal().remove(i);
                    }
                }
                adminUsuarioNormal.escrbirArchivo();
                JOptionPane.showMessageDialog(null, "Se ha eliminado su usuario correctamente. ");
                jd_UsuarioNormal.dispose();
            }
        } catch (Exception e) {
        }    }//GEN-LAST:event_bt_eliminarseSistemaMouseClicked

    private void jtree_solicitudesAmistadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree_solicitudesAmistadMouseClicked

        if (evt.isMetaDown()) {
            
            jpopup_opciones.show(evt.getComponent(), evt.getX(), evt.getY());
            jpopup_opciones.setVisible(true);
            
        }

    }//GEN-LAST:event_jtree_solicitudesAmistadMouseClicked

    private void bt_agregarAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarAmigosMouseClicked

        String agregar = JOptionPane.showInputDialog(null, "Ingrese el nombre de la persona a agregar: ");
        String nombre = JOptionPane.showInputDialog(null, "Ingrese su nombre porfavor: ");

        for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) {
            if (adminUsuarioNormal.getUsuarioNormal().get(i).getNombreCompleto().equals(nombre)) {
                adminUsuarioNormal.getUsuarioNormal().get(i).getSolicitudes().add(agregar);
                JOptionPane.showMessageDialog(null, "Solicitud de amistad enviada.");
            }
        }


    }//GEN-LAST:event_bt_agregarAmigosMouseClicked

    private void bt_agregarAmigosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarAmigosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_agregarAmigosMouseEntered

    private void jmi_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_aceptarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_aceptarMouseClicked

    private void jmi_rechazarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmi_rechazarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_rechazarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_registrarse;
    private javax.swing.JButton bt_agregarAmigos;
    private javax.swing.JButton bt_eliminarseSistema;
    private javax.swing.JButton bt_iniciarSesion;
    private javax.swing.JButton bt_modificarInformacion;
    private javax.swing.JButton bt_seleccionarimagen;
    private com.toedter.calendar.JDateChooser dt_fechaNacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JDialog jd_UsuarioAdministrador;
    private javax.swing.JDialog jd_UsuarioNormal;
    private javax.swing.JDialog jd_crearUsuario;
    private javax.swing.JDialog jd_logIn;
    private javax.swing.JMenuItem jmi_aceptar;
    private javax.swing.JMenuItem jmi_rechazar;
    private javax.swing.JPopupMenu jpopup_opciones;
    private javax.swing.JTable jt_informacionPersonalUsuarioComun;
    private javax.swing.JTable jt_usuariosGenerales;
    private javax.swing.JTable jt_usuariosSolicitudes;
    private javax.swing.JTree jtree_listaAmigos;
    private javax.swing.JTree jtree_solicitudesAmistad;
    private javax.swing.JLabel lb_fotopapeleta;
    private javax.swing.JPasswordField ps_contraseña;
    private javax.swing.JRadioButton rb_Administrador;
    private javax.swing.JRadioButton rb_Normal;
    private javax.swing.JTextField tf_contraseñaLogIn;
    private javax.swing.JTextField tf_correoElectronico;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuarioLogIn;
    // End of variables declaration//GEN-END:variables
ArrayList<Object> comentarios = new ArrayList();
    AdministradorUsuarioNormal adminUsuarioNormal = new AdministradorUsuarioNormal("./UsuarioNormal.bin");
    AdministradorUsuarioAdmin adminUsuarioAdmin = new AdministradorUsuarioAdmin("./UsuarioAdministrador.bin");
}
